apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  APP_MESSAGE: " Штирлиц всю ночь писал Terraform. Утром инфраструктура не поднялась. «Идемпотентность», — подумал Штирлиц, запуская всё в десятый раз."